spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/college
    password: 1000239596
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
